AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCStackName:
    Description: Cloudformation stack name of the VPC stack
    Type: String
  # https://aws.amazon.com/ec2/instance-types/
  EC2InstanceType: 
    Description: Instance type for iperf server and client
    Type: String
    Default: m5.xlarge
    AllowedValues:
      # General Purpose 
      - t2.micro
      - m5.xlarge
      - m5.2xlarge
      - m5.4large
  IPAddressIperfClient:
    Description: Local IP address of wrk
    Type: String
    MinLength: "7"
    MaxLength: "15"
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP of the form x.x.x.x, in the subnet CIDR range 10.0.0.0/16 defined in this template.
  IPAddressIperfServer:
    Description: Local IP address of the web server
    Type: String
    MinLength: "7"
    MaxLength: "15"
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: must be a valid IP of the form x.x.x.x, in the subnet CIDR range 10.0.0.0/16 defined in this template.

Resources:
  # Define EC2 instance for iperf client and server
  EC2InstanceIperfClient:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0d7ed3ddb85b521a6"
      InstanceType: !Ref EC2InstanceType
      # You should create an EC2 key pair in advance, as there is no key-pair resource in CloudFormation
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-keypair.html
      KeyName: "demo-key-pair"
      # To allow running commands via SSM
      IamInstanceProfile: {'Fn::ImportValue': !Sub '${VPCStackName}-InstanceProfile'}
      # https://aws.amazon.com/premiumsupport/knowledge-center/network-throughput-benchmark-linux-ec2/
      UserData:
        Fn::Base64: |
            #!/bin/bash
            yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum -y install iperf
            yum -y install iperf3
            yum -y install git
            cd /home/ec2-user
            git clone https://github.com/richardimaoka/aws-iperf
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - {'Fn::ImportValue': !Sub '${VPCStackName}-SecurityGroup'}
          SubnetId: {'Fn::ImportValue': !Sub '${VPCStackName}-Subnet'}
          PrivateIpAddresses:
            - PrivateIpAddress: !Ref IPAddressIperfClient
              Primary: true
      Tags:
      - Key: Name
        Value: iperf-client-instance
  EC2InstanceIperfServer:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0d7ed3ddb85b521a6"
      InstanceType: !Ref EC2InstanceType
      # You should create an EC2 key pair in advance, as there is no key-pair resource in CloudFormation
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-keypair.html
      KeyName: "demo-key-pair"
      # To allow running commands via SSM
      IamInstanceProfile: {'Fn::ImportValue': !Sub '${VPCStackName}-InstanceProfile'}
      # https://aws.amazon.com/premiumsupport/knowledge-center/network-throughput-benchmark-linux-ec2/
      UserData:
        Fn::Base64: |
            #!/bin/bash
            yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum -y install iperf
            yum -y install iperf3
            cd /home/ec2-user
            git clone https://github.com/richardimaoka/aws-iperf
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - {'Fn::ImportValue': !Sub '${VPCStackName}-SecurityGroup'}
          SubnetId: {'Fn::ImportValue': !Sub '${VPCStackName}-Subnet'}
          PrivateIpAddresses:
            - PrivateIpAddress: !Ref IPAddressIperfServer
              Primary: true
      Tags:
      - Key: Name
        Value: iperf-server-instance
